import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Thai font not available in jsPDF by default — use Unicode-safe approach
// with autoTable which handles text better

interface DashboardData {
  businessName: string;
  month: string; // "พฤษภาคม 2567"
  boxes: Record<string, any>;
  verdict: { level: string; messages: string[] };
}

const BOX_ORDER = [
  { key: '1_grossSales', label: 'ยอดขายรวม', format: 'currency' },
  { key: '2_salesMix', label: 'สัดส่วน สด/เชื่อ', format: 'mix' },
  { key: '3_grossMargin', label: 'Gross Margin', format: 'percent' },
  { key: '4_netProfit', label: 'Net Profit', format: 'currency' },
  { key: '5_expenseRatio', label: 'ค่าใช้จ่ายกินยอดขาย', format: 'percent' },
  { key: '6_leakNote', label: 'จุดรั่วเดือนนี้', format: 'text' },
  { key: '7_cashIn', label: 'Cash In', format: 'currency' },
  { key: '8_arBalance', label: 'ลูกหนี้ค้างเก็บ', format: 'currency' },
  { key: '9_apBalance', label: 'เจ้าหนี้ค้างจ่าย', format: 'currency' },
  { key: '10_runway', label: 'Cash Runway', format: 'number' },
];

function fmtValue(box: any): string {
  if (!box) return '-';
  if (box.display) return box.display;
  if (box.value == null && box.months == null) return '-';

  if (box.format === 'currency') return Number(box.value).toLocaleString('en-US') + ' baht';
  if (box.format === 'percent') return (Number(box.value) * 100).toFixed(1) + '%';
  if (box.format === 'text') return String(box.value || '-');
  if (box.format === 'mix') return `Cash ${((box.cashPct || 0) * 100).toFixed(0)}% / Credit ${((box.creditPct || 0) * 100).toFixed(0)}%`;
  if (box.months != null) return box.months.toFixed(1) + ' months';
  return String(box.value);
}

function fmtColor(box: any): string {
  if (!box?.color) return '-';
  if (box.color === 'green') return 'Good';
  if (box.color === 'yellow') return 'Warning';
  if (box.color === 'red') return 'Critical';
  return '-';
}

export function exportDashboardPDF(data: DashboardData) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Header
  doc.setFontSize(18);
  doc.text('WinWin Analyzer — Owner Dashboard', 14, 20);

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`${data.businessName} | ${data.month}`, 14, 28);

  // Verdict
  const verdictText = data.verdict.messages.join(' | ');
  const verdictLevel = data.verdict.level === 'ok' ? 'GOOD' : data.verdict.level === 'warning' ? 'WARNING' : 'CRITICAL';

  doc.setFontSize(10);
  doc.setTextColor(
    data.verdict.level === 'critical' ? 200 : data.verdict.level === 'warning' ? 180 : 0,
    data.verdict.level === 'ok' ? 150 : 0,
    0
  );
  doc.text(`Status: ${verdictLevel}`, 14, 36);
  doc.setTextColor(60);
  doc.text(verdictText, 14, 42, { maxWidth: 180 });

  // Dashboard table
  const tableData = BOX_ORDER.map((item) => {
    const box = data.boxes[item.key];
    return [item.label, fmtValue(box), fmtColor(box)];
  });

  autoTable(doc, {
    startY: 50,
    head: [['Metric', 'Value', 'Status']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [30, 30, 31], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 80 },
      2: { cellWidth: 30 },
    },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by WinWin Analyzer | winwinwealth.co', 14, pageHeight - 10);
  doc.text(new Date().toLocaleDateString('th-TH', { year: 'numeric', month: 'long', day: 'numeric' }), 14, pageHeight - 6);

  // Download
  const filename = `dashboard-${data.month.replace(/\s/g, '-')}.pdf`;
  doc.save(filename);
}
